### PR TITLE
Internalize math functions

### PR DESCRIPTION
**Pull request by brianmcmichael**
* Uses internal for ds-math functions instead of public
* Fixes shadowed declaration warnings
* Fixes a warning in one of the tests

This needs a pass to determine whether everything else is appropriately `external` or `public`, there seems to be some inconsistency here.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Is the idea to redeploy it?

**Comment by gbalabasquer** [comment]
Is the idea to redeploy it?

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Comment by kmbarry1** [comment]
> Is the idea to redeploy it?

Good question...this should reduce the size of the function table by a good bit, so might have an impact on gas costs. If we've already given the deployed address to integrators maybe not. Also it may not be worth our ETH to deploy again.

**Review by hexonaut — APPROVED** [review]
LGTM. Should probably tag the current release for Lido.

Keep in mind that this is under a proxy, so we can update these internal structures without any issue.

**Comment by hexonaut** [comment]
Tagged a release: https://github.com/makerdao/dss-crop-join/releases/tag/v1.0.0

We can merge this now imo

**Pull request merged**
